language: rust

rust:
  - stable

jobs:
  include:
    - os: osx
      arch: amd64
      env: ENV_NAME="x86_64-apple-darwin"
    - os: windows
      arch: amd64
      env: ENV_NAME="x86_64-pc-windows-msvc"
    - os: linux
      dist: bionic
      arch: amd64
      env: ENV_NAME="x86_64-unknown-linux-gnu"
    - os: linux
      dist: bionic
      arch: arm64
      env: ENV_NAME="aarch64-unknown-linux-gnu"

install:
  - cargo build --release

script:
  - mkdir ssvmup-$TRAVIS_TAG-$ENV_NAME
  - cp ./target/release/ssvmup ssvmup-$TRAVIS_TAG-$ENV_NAME
  - tar -czf ssvmup-$TRAVIS_TAG-$ENV_NAME.tar.gz ssvmup-$TRAVIS_TAG-$ENV_NAME

deploy:
  - provider: releases
    overwrite: false
    cleanup: false
    token: $GITHUB_TOKEN
    file: "ssvmup-$TRAVIS_TAG-$ENV_NAME.tar.gz"
    name: Release $TRAVIS_TAG
    edge: true
    on:
      tags: true
  - provider: npm
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    src: ./npm
    edge: true
    on:
      tags: true
      condition: $ENV_NAME = "x86_64-apple-darwin"
